const userData = {
  githubUsername: "slitheringblob",
  name: "Jaydeep Ganatra",
  designation: "Senior Software Engineer",
  roleSummary: "Applied ML, agents, and product engineering.",
  avatarUrl: "/avatar.jpg",
  email: "work@jaydeepganatra.dev",
  phone: "+91 9408657603",
  address: "Surat, Gujarat, India",
  resumeUrl: "/JaydeepGanatraResume.pdf",
  hero: {
    title: "I build applied machine learning systems, agents, and product software.",
    intro:
      "My work sits at the intersection of model-driven systems and product delivery: retrieval, backend services, cloud infrastructure, and interfaces people can actually use.",
    currentRole: "Senior Software Engineer / Design Principal at thinkbridge",
    currentRoleUrl: "https://thinkbridge.com/",
    currentSummary:
      "Building and using an internal no-code platform that turns concrete requirements into full-fledged systems solving business problems for small and medium businesses at low cost.",
    stats: [
      {
        label: "Focus",
        value: "Applied machine learning with product taste",
      },
      {
        label: "Works with",
        value: "Python, applied ML, Agents, AWS, GCP, Azure",
      },
      {
        label: "Based in",
        value: "Surat, India",
      },
    ],
  },
  about: {
    title: "About",
    description: [
      "I started writing code in school and never really stopped. Since then I have worked across banking, product engineering, internal platforms, and ML-adjacent tooling.",
      "I like solving hard problems with a practical bias: clear interfaces, maintainable systems, and enough ambition to make the work feel alive.",
      "When I am strongest, I am usually somewhere between product instincts and infrastructure discipline.",
    ],
    callout:
      "Currently building at thinkbridge, with recent work spanning platform engineering, data pipelines, and dense retrieval for code.",
    companyURL: "https://thinkbridge.com/",
  },
  projects: [
    {
      title: "Freeder",
      link: "https://github.com/slitheringblob/Freeder",
      imgUrl: "/freeder.svg",
      year: "2025",
      category: "RSS Reader",
      summary:
        "A pure and opinionated RSS feed reader built with HTML, CSS, Tailwind, and FastAPI.",
      stack: ["HTML", "CSS", "Tailwind CSS", "FastAPI"],
      accent: "var(--accent-red)",
    },
    {
      title: "Nosk",
      link: "https://github.com/slitheringblob/nosk",
      imgUrl: "/nosk.svg",
      year: "2025",
      category: "Notes App",
      summary:
        "A note-taking app in progress, designed to sync cleanly across your devices.",
      stack: ["Notes", "Sync", "Product"],
      accent: "var(--accent-blue)",
    },
    {
      title: "Tache",
      link: "https://github.com/slitheringblob/tache",
      imgUrl: "/tache.svg",
      year: "2023",
      category: "Productivity App",
      summary:
        "A lightweight task manager built around quick capture, simple organization, and minimal friction.",
      stack: ["React", "Firebase", "CSS"],
      accent: "var(--accent-red)",
    },
<<<<<<< HEAD
    experience: [
      {
        title: "Senior Software Engineer",
        company: "thinkbridge",
        year: "2024",
        companyLink: "https://thinkbridge.com",
        desc: "Worked as a Machine Learning Fellow to build an engine capable of Dense Retrival for Code for multiple languages. ",
      },
      {
        title: "Senior Software Engineer",
        company: "thinkbridge",
        year: "2023",
        companyLink: "https://thinkbridge.com",
        desc: "Responsible for the entire development of the Karmic Platform. Also taking on features in other projects with Elixir,Phoenix LiveView. ",
      },
      {
        title: "Software Engineer",
        company: "thinkbridge",
        year: "2022",
        companyLink: "https://thinkbridge.com",
        desc: "Responsible for all new full-stack feature requests for the Karmic Platform. Also worked as a Data Engineer for creating data ingestion pipelines using AWS and PySpark.",
      },
      {
        title: "Associate Software Engineer",
        company: "thinkbridge",
        year: "2021",
        companyLink: "https://thinkbridge.com",
        desc: "Responsible for all new backend feature requests for the Karmic Platform.",
      },
      {
        title: "Deputy Manager",
        company: "HDFC Bank",
        year: "2020",
        companyLink: "https://www.hdfcbank.com/",
        desc: "Responsible for developing an entire Vendor Payments Solution using Flask and MySQL. Acted as the SPOC for Performance Engineering for the entire SeCOE",
      },
      {
        title: "Engineering Trainee",
        company: "HDFC Bank",
        year: "2019",
        companyLink: "https://www.hdfcbank.com/",
        desc: "Started my professional career as a technical analyst with the Software Engineering Centre of Excellence at India's largest private bank.",
      },
      {
        title: "Graduation",
        company: "NMIMS, Mumbai.",
        year: "2019",
        companyLink: "https://engineering.nmims.edu/",
        desc: "Bachelors in Computer Science and Engineering.",
      },
      {
        title: "Internship",
        company: "OMIFCO SAOC., Sur, Oman",
        year: "2017",
        companyLink: "https://www.omifco.com/",
        desc: "Worked as a DBA shadow. Implemented stored procedures and process automation for daily data backups.",
      },
      {
        title: "High School",
        company: "Kendriya Vidhyalaya, Surat",
        year: "2015",
        companyLink: "https://no2hajirasurat.kvs.ac.in/",
        desc: "PCM and a failed JEE asiprant.",
      },
    ],
    resumeUrl:
      "/JGResumeAugust2025.pdf",
    socialLinks: {
      instagram: "https://instagram.com/jaydeep.11",
      twitter: "https://twitter.com/jaydeepganatra",
      linkedin: "https://www.linkedin.com/in/jaydeep-ganatra/",
      github: "https://github.com/slitheringblob",
=======
    {
      title: "Identicon",
      link: "https://github.com/slitheringblob/identicon",
      imgUrl: "/identicon.svg",
      year: "2022",
      category: "Generative Utility",
      summary:
        "A deterministic avatar generator that turns text input into consistent geometric identities.",
      stack: ["Elixir", "Phoenix"],
      accent: "var(--accent-blue)",
>>>>>>> 60bae2c (buncha updates - mainly CVE fixes)
    },
    {
      title: "ReactCalc",
      link: "https://github.com/slitheringblob/reactcalc",
      imgUrl: "/reactcalc.svg",
      year: "2021",
      category: "Frontend Experiment",
      summary:
        "A small UI build used to work through state management, interaction details, and component structure.",
      stack: ["React", "JavaScript"],
      accent: "var(--accent-gold)",
    },
    {
      title: "Ezrag",
      link: "https://github.com/slitheringblob/ezrag",
      imgUrl: "/ezrag.svg",
      year: "2025",
      category: "RAG Tooling",
      summary:
        "A lightweight RAG system built with Streamlit, ChromaDB, and Hugging Face sentence transformers.",
      stack: ["Python", "Streamlit", "ChromaDB", "Sentence Transformers"],
      accent: "var(--accent-blue)",
    },
    {
      title: "Portfolio",
      link: "https://github.com/slitheringblob/slitheringblob.github.io",
      imgUrl: "/portfolio-site.svg",
      year: "2026",
      category: "Personal Site",
      summary:
        "This portfolio, rebuilt to present projects and technical focus with a cleaner structure and stronger visual voice.",
      stack: ["Next.js", "Tailwind CSS"],
      accent: "var(--accent-green)",
    },
    {
      title: "Shopbridge",
      link: "https://github.com/slitheringblob/shopbridge-api",
      imgUrl: "/shopbridge.svg",
      year: "2020",
      category: "Backend API",
      summary:
        "A commerce API project centered on service boundaries, persistence, and straightforward backend design.",
      stack: ["Python", "MySQL", "REST"],
      accent: "var(--accent-red)",
    },
  ],
  stack: [
    "Python",
    "Elixir",
    "React",
    "Phoenix",
    "Next.js",
    "AWS",
    "Docker",
    "PostgreSQL",
    "MongoDB",
    "Git",
  ],
  experience: [
    {
      title: "Senior Software Engineer",
      company: "thinkbridge",
      year: "2025",
      companyLink: "https://thinkbridge.com",
      desc: "Built a system that creates pathways for conversation agents used by one of the biggest players in the recruitment space worldwide.",
    },
    {
      title: "Senior Software Engineer",
      company: "thinkbridge",
      year: "2024",
      companyLink: "https://thinkbridge.com",
      desc: "Worked as a Machine Learning Fellow, contributing to a dense retrieval engine for code across multiple programming languages.",
    },
    {
      title: "Senior Software Engineer",
      company: "thinkbridge",
      year: "2023",
      companyLink: "https://thinkbridge.com",
      desc: "Led development on the Karmic platform and contributed features in adjacent products using Elixir and Phoenix LiveView.",
    },
    {
      title: "Software Engineer",
      company: "thinkbridge",
      year: "2022",
      companyLink: "https://thinkbridge.com",
      desc: "Built new full-stack features for the Karmic platform and supported data ingestion work with AWS and PySpark.",
    },
    {
      title: "Associate Software Engineer",
      company: "thinkbridge",
      year: "2021",
      companyLink: "https://thinkbridge.com",
      desc: "Focused on backend feature delivery and platform improvements for production systems.",
    },
    {
      title: "Deputy Manager",
      company: "HDFC Bank",
      year: "2020",
      companyLink: "https://www.hdfcbank.com/",
      desc: "Built a vendor payments solution with Flask and MySQL and acted as a performance engineering point of contact for the wider engineering group.",
    },
    {
      title: "Engineering Trainee",
      company: "HDFC Bank",
      year: "2019",
      companyLink: "https://www.hdfcbank.com/",
      desc: "Started my career in the Software Engineering Centre of Excellence, learning how large organizations operate and ship software.",
    },
    {
      title: "Graduation",
      company: "NMIMS, Mumbai",
      year: "2019",
      companyLink: "https://engineering.nmims.edu/",
      desc: "Completed a bachelor's degree in Computer Science and Engineering.",
    },
    {
      title: "Internship",
      company: "OMIFCO SAOC, Sur, Oman",
      year: "2017",
      companyLink: "https://www.omifco.com/",
      desc: "Worked close to database operations and implemented automation around regular data backups.",
    },
    {
      title: "High School",
      company: "Kendriya Vidhyalaya, Surat",
      year: "2015",
      companyLink: "https://no2hajirasurat.kvs.ac.in/",
      desc: "The years where programming stopped being a subject and became the thing I wanted to keep doing.",
    },
  ],
  socialLinks: {
    instagram: "https://instagram.com/jaydeep.11",
    twitter: "https://twitter.com/jaydeepganatra",
    linkedin: "https://www.linkedin.com/in/jaydeep-ganatra/",
    github: "https://github.com/slitheringblob",
  },
};

export default userData;
